"""added model tags table

Revision ID: 404d1328dd98
Revises: 54ee1a8c8433
Create Date: 2026-02-04 16:01:48.689230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404d1328dd98'
down_revision = '54ee1a8c8433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['agent_id', 'model_name'], ['model.agent_id', 'model.model_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'model_name', 'name', name='uq_tag_model_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    # ### end Alembic commands ###
