"""added tables for storing chat history

Revision ID: 7683fdc00670
Revises: 2109fd087fde
Create Date: 2025-12-23 15:02:24.548213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7683fdc00670'
down_revision = '2109fd087fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_create_datetime'), ['create_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_user_id'), ['user_id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('load_duration', sa.Integer(), nullable=True),
    sa.Column('prompt_eval_count', sa.Integer(), nullable=True),
    sa.Column('prompt_eval_duration', sa.Integer(), nullable=True),
    sa.Column('eval_count', sa.Integer(), nullable=True),
    sa.Column('eval_duration', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_create_datetime'), ['create_datetime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_create_datetime'))
        batch_op.drop_index(batch_op.f('ix_message_chat_id'))

    op.drop_table('message')
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_create_datetime'))

    op.drop_table('chat')
    # ### end Alembic commands ###
