"""added model reasoning to messages

Revision ID: a177e38e6a85
Revises: 404d1328dd98
Create Date: 2026-02-15 20:15:10.727321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a177e38e6a85'
down_revision = '404d1328dd98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_reasoning', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('model_reasoning')

    # ### end Alembic commands ###
