"""added agent and model to chat

Revision ID: 04fa50917e70
Revises: 5c276c409a26
Create Date: 2025-12-26 11:13:00.519483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04fa50917e70'
down_revision = '5c276c409a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('model_name', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_chat_agent_id', 'agent', ['agent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_chat_model_agent_model', 'model', ['agent_id', 'model_name'], ['agent_id', 'model_name'], ondelete='CASCADE')

    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_model_agent_id_model_name', ['agent_id', 'model_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_constraint('uq_model_agent_id_model_name', type_='unique')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_model_agent_model', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('model_name')
        batch_op.drop_column('agent_id')

    # ### end Alembic commands ###
