"""added knowledge_base table for RAG

Revision ID: 35df76d7b547
Revises: 04fa50917e70
Create Date: 2025-12-31 14:59:04.660668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35df76d7b547'
down_revision = '04fa50917e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document_filename', sa.String(length=255), nullable=False),
    sa.Column('document_content', sa.Text(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_base_create_datetime'), ['create_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_base_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_base', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_base_user_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_base_create_datetime'))

    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
